# Generated by Django 4.2.16 on 2024-09-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Board',
        ),
    ]
